version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sns-lambda-gateway-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8twyf319ckls"
s3_prefix = "sns-lambda-gateway-demo"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
